services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: clinicai-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  account:
    build: ./account
    container_name: clinicai-account
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    depends_on:
      - rabbitmq

  billing:
    build: ./billing
    container_name: clinicai-billing
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    depends_on:
      - rabbitmq

  data:
    build: ./data
    container_name: clinicai-data
    ports:
      - "8083:8083"
    environment:
      - SERVER_PORT=8083
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    depends_on:
      - rabbitmq

  encounter:
    build: ./encounter
    container_name: clinicai-encounter
    ports:
      - "8087:8087"
    environment:
      - SERVER_PORT=8087
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    depends_on:
      - rabbitmq

  labtest:
    build: ./labtest
    container_name: clinicai-labtest
    ports:
      - "8088:8088"
    environment:
      - SERVER_PORT=8088
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    depends_on:
      - rabbitmq

  labtest-list:
    build: ./labtest-list
    container_name: clinicai-labtest-list
    ports:
      - "8085:8085"
    environment:
      - SERVER_PORT=8085
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    depends_on:
      - rabbitmq

  email:
    build: ./email
    container_name: clinicai-email
    ports:
      - "8089:8089"
    environment:
      - SERVER_PORT=8089
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    depends_on:
      - rabbitmq
